version: '3.8'

services:
  # --- PostgreSQL & pgAdmin ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: samil
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # --- Redis & RedisInsight ---
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    # Eğer Redis'e şifre koymak istersen command satırını aç:
    # command: redis-server --requirepass myredispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_ui
    ports:
      - "5540:5540"
    depends_on:
      - redis

  # --- Server ---
  server:
    build: .
    command: ["./server"]
    container_name: notification_server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: samil
      DB_PASSWORD: mysecretpassword
      DB_NAME: myappdb
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: "8080"
      WEBHOOK_URL: https://webhook.site/4b9f3602-73b6-44e5-8751-dfa02509efd1
    depends_on:
      - db
      - redis

  # --- Worker ---
  worker:
    build: .
    command: ["./worker"]
    container_name: notification_worker
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: samil
      DB_PASSWORD: mysecretpassword
      DB_NAME: myappdb
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WEBHOOK_URL: https://webhook.site/4b9f3602-73b6-44e5-8751-dfa02509efd1
      WORKER_CONCURRENCY: 20
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: